#!/bin/sh
bspc rule -r "*"

## EXPORTS
# defaults
[ -z "$TERMINAL" ] && export  TERMINAL="st"
[ -z "$BROWSER" ] && export BROWSER="chromium"

## AUTOSTART
# Kill the program before launching it
xrdb $HOME/.Xresources &
pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x lemon >/dev/null || lemon &
$HOME/.fehbg &

## MONITORS
bspc monitor LVDS-1 -d 1 2 3 4 5 6
bspc monitor VGA-1 -d 7 8 9 0
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

## WINDOW SPAWNING
bspc config automatic_scheme alternate
bspc config initial_polarity second_child

## POINTER
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none
bspc config focus_follows_pointer true

## COLORS
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

## DESKTOP
bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 0

## RULES
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
